### ISSUE TITLE
[0.5pt] Find external API - group task

### ISSUE THREAD

**Issue by steveWDamesJr** [steveWDamesJr/javascript-capstone-project#20]
Find an API to base the development of the webapp around it. The API should allow you to
  - Get a list of items with a unique item id (or generate the unique id).
  - For a given item, get detailed information about it.
choose an APIs that doesn't need authentication. if you select an API that requires authentication, you should implement it on your own. Also, if you select an API that provides image resources your webapp will be more visual.
--- There are two people in this project.
Steve W Dames Jr.
Bereket Retta
Project link: https://github.com/steveWDamesJr/javascript-capstone-project/projects/2

**Comment by steveWDamesJr** [comment]
We've chosen the TVmaze Api reference attached below:

 https://www.tvmaze.com/api

**Comment by micheaol** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 

## Required Changes ♻️
 - For a team with 2 people: 
   - Please ensure that all cards with `Student C` are removed.
   - Please ensure that the number of cards on the board should be equal to 15.
   - Please ensure that ll cards with `group task` in the title should be assigned to someone.
   - Please ensure that all cards are assigned to team members. See the example below:

![Assigned cards example](https://user-images.githubusercontent.com/10332499/153828596-277121e1-ff7c-42b5-95c4-ebabd73c0cc4.PNG)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by steveWDamesJr** [comment]
Thank you for your review:


-     Please ensure that all cards with Student C are removed. ✔️ 
-     Please ensure that the number of cards on the board should be equal to 15. ✔️ 
-     Please ensure that ll cards with group task in the title should be assigned to someone. ✔️ 
-     Please ensure that all cards are assigned to team members. See the example below: ✔️ 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/81635839/153834445-6bef3c40-7b4f-416b-a72c-c53b39de8fb2.png">

**Comment by medaminedev66** [comment]
Hi @steveWDamesJr and @BereketRetta, 

Your project is complete! You can start working on your capstone project 🚢  
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
